"""add city and review_count to restaurants

Revision ID: 4983cf9af2f1
Revises: 83e834274736
<<<<<<< HEAD
Create Date: 2026-05-13 11:12:34.777359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4983cf9af2f1'
down_revision: Union[str, None] = '83e834274736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('review_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_column('restaurants', 'review_count')
    op.drop_column('restaurants', 'city')
    # ### end Alembic commands ###
=======
Create Date: 2026-05-13
>>>>>>> 4218ac8648f7f5938629eab46928395c02bc588b

"""
from alembic import op
import sqlalchemy as sa

revision = '4983cf9af2f1'
down_revision = '83e834274736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('restaurants',
        sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('restaurants',
        sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_restaurants_city', 'restaurants', ['city'])


def downgrade() -> None:
    op.drop_index('ix_restaurants_city', table_name='restaurants')
    op.drop_column('restaurants', 'review_count')
    op.drop_column('restaurants', 'city') 

<<<<<<< HEAD
 
"""
=======
 
>>>>>>> 4218ac8648f7f5938629eab46928395c02bc588b
