"""add_image_url_to_restaurants

Revision ID: 589526846f91
Revises: 4983cf9af2f1
Create Date: 2026-05-14 13:18:45.618213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '589526846f91'
down_revision: Union[str, None] = '4983cf9af2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('reservations', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('reservations', sa.Column('number_of_people', sa.Integer(), nullable=False))
    op.drop_column('reservations', 'reservation_time')
    op.drop_column('reservations', 'num_people')
    op.add_column('restaurants', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image_url')
    op.add_column('reservations', sa.Column('num_people', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservations', sa.Column('reservation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reservations', 'number_of_people')
    op.drop_column('reservations', 'time')
    op.drop_column('reservations', 'date')
    # ### end Alembic commands ###
